kind = "web"
previewPath = "/"
title = "Smart Garbage Management"
version = "1.0.0"
id = "artifacts/smart-garbage"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19665

[services.development]
run = "pnpm --filter @workspace/smart-garbage run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smart-garbage", "run", "build" ]
publicDir = "artifacts/smart-garbage/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19665"
BASE_PATH = "/"
